<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Additional Information') ?></span></legend>
    <p>
    <div class="field regulation">
        <label for="regulation" class="label"><span><?php /* @escapeNotVerified */
                echo __('Username') ?></span></label>
        <div class="control">
            <input type="text" name="username" id="username" title="<?php /* @escapeNotVerified */ echo __('Username') ?>" class="input-text" data-validate="{required:false}">
        </div>
    </div>
    </p>
</fieldset>
