<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \LSL\Theme\Block\Html\Header $block
 */
$welcomeMessage = $block->getWelcome();
?>

<div class="navbar-left">
    <ul class="social-icons">
        <li><a href="https://www.facebook.com/lovestruckldn/" target="_blank"  title="Facebook"><span class="icon facebook"></span><span class="label hidden">Facebook</span></a></li>
        <li><a href="https://www.pinterest.co.uk/LovestruckLDN/" target="_blank"  title="Pinterest"><span class="icon pinterest"></span><span class="label hidden">Pinterest</span></a></li>
        <li><a href="https://www.instagram.com/lovestruckldn/" target="_blank"  title="Instagram"><span class="icon instagram"></span><span class="label hidden">Instagram</span></a></li>
    </ul>
</div>

<div class="navbar-center">
    <p><?= $block->escapeHtml($welcomeMessage) ?></p>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "customer": {
                    "component": "Magento_Customer/js/view/customer"
                }
            }
        }
    }
}
</script>